import { COLOR } from "./colors";

export const COMMON_THEME = {
  HEADING: COLOR.GREY_900,
  PAPER: COLOR.PAPER,
  BACKGROUND_DEFAULT: COLOR.PAPER,
  BACKGROUND: COLOR.PRIMARY_LIGHT,
  DARK_TEXT_PRIMARY: COLOR.GREY_700,
  DARK_TEXT_SECONDARY: COLOR.GREY_500,
  TEXT_DARK: COLOR.GREY_900,
  MENU_SELECTED: COLOR.SECONDARY_DARK,
  MENU_SELECTED_BACK: COLOR.SECONDARY_LIGHT,
  DIVIDER: COLOR.GREY_200,
} as const;
