import { createLookup } from "@/shared/utils";
import { ExpenseCategory } from "../types/expense";
import {
  ExpenseGroupCategory,
  IncomeCategory,
  IncomeGroupCategory,
} from "../types/shared";

export const EXPENSE_CATEGORIES: ExpenseCategory[] = [
  "FOOD",
  "TAKEAWAY",
  "ALCOHOL",
  "RENT",
  "UTILITIES",
  "MAINTENANCE",
  "PUBLIC_TRANSPORT",
  "FUEL",
  "CAR",
  "DOCTOR",
  "PHARMACY",
  "GYM",
  "CINEMA",
  "BOOKS",
  "OTHER",
];

export const EXPENSE_CATEGORY = createLookup(EXPENSE_CATEGORIES);

export const EXPENSE_GROUP_CATEGORIES = [
  "SHOPPING",
  "HOUSING",
  "TRANSPORT",
  "HEALTHCARE",
  "ENTERTAINMENT",
  "OTHER",
] as const;

export const EXPENSE_GROUP_CATEGORY = createLookup([
  ...EXPENSE_GROUP_CATEGORIES,
]);

export const EXPENSE_GROUP_CATEGORY_BY_CATEGORY: Record<
  ExpenseCategory,
  ExpenseGroupCategory
> = {
  FOOD: EXPENSE_GROUP_CATEGORY.SHOPPING,
  TAKEAWAY: EXPENSE_GROUP_CATEGORY.SHOPPING,
  ALCOHOL: EXPENSE_GROUP_CATEGORY.SHOPPING,
  RENT: EXPENSE_GROUP_CATEGORY.HOUSING,
  UTILITIES: EXPENSE_GROUP_CATEGORY.HOUSING,
  MAINTENANCE: EXPENSE_GROUP_CATEGORY.HOUSING,
  PUBLIC_TRANSPORT: EXPENSE_GROUP_CATEGORY.TRANSPORT,
  FUEL: EXPENSE_GROUP_CATEGORY.TRANSPORT,
  CAR: EXPENSE_GROUP_CATEGORY.TRANSPORT,
  DOCTOR: EXPENSE_GROUP_CATEGORY.HEALTHCARE,
  PHARMACY: EXPENSE_GROUP_CATEGORY.HEALTHCARE,
  GYM: EXPENSE_GROUP_CATEGORY.ENTERTAINMENT,
  CINEMA: EXPENSE_GROUP_CATEGORY.ENTERTAINMENT,
  BOOKS: EXPENSE_GROUP_CATEGORY.ENTERTAINMENT,
  OTHER: EXPENSE_GROUP_CATEGORY.OTHER,
};

export const EXPENSE_CATEGORY_LABEL: Record<ExpenseCategory, string> = {
  [EXPENSE_CATEGORY.ALCOHOL]: "Alkohol",
  [EXPENSE_CATEGORY.BOOKS]: "Książki",
  [EXPENSE_CATEGORY.CAR]: "Samochód",
  [EXPENSE_CATEGORY.CINEMA]: "Kino",
  [EXPENSE_CATEGORY.DOCTOR]: "Lekarz",
  [EXPENSE_CATEGORY.FOOD]: "Jedzenie",
  [EXPENSE_CATEGORY.FUEL]: "Paliwo",
  [EXPENSE_CATEGORY.GYM]: "Siłownia",
  [EXPENSE_CATEGORY.MAINTENANCE]: "Naprawy",
  [EXPENSE_CATEGORY.OTHER]: "Inne",
  [EXPENSE_CATEGORY.PHARMACY]: "Leki",
  [EXPENSE_CATEGORY.PUBLIC_TRANSPORT]: "Komunikacja miejska",
  [EXPENSE_CATEGORY.RENT]: "Czynsz",
  [EXPENSE_CATEGORY.TAKEAWAY]: "Na wynos",
  [EXPENSE_CATEGORY.UTILITIES]: "Media",
};

export const EXPENSE_GROUP_CATEGORY_LABEL: Record<
  ExpenseGroupCategory,
  string
> = {
  [EXPENSE_GROUP_CATEGORY.ENTERTAINMENT]: "Rozrywka",
  [EXPENSE_GROUP_CATEGORY.HEALTHCARE]: "Opieka zdrowotna",
  [EXPENSE_GROUP_CATEGORY.HOUSING]: "Mieszkanie",
  [EXPENSE_GROUP_CATEGORY.OTHER]: "Inne",
  [EXPENSE_GROUP_CATEGORY.SHOPPING]: "Zakupy",
  [EXPENSE_GROUP_CATEGORY.TRANSPORT]: "Transport",
};

export const INCOME_CATEGORIES: IncomeCategory[] = [
  "DIVIDENDS",
  "FULL_TIME",
  "FREELANCE",
  "INTEREST",
  "OTHER",
  "PART_TIME",
  "RENTAL_INCOME",
];

export const INCOME_CATEGORY = createLookup(INCOME_CATEGORIES);

export const INCOME_GROUP_CATEGORIES = [
  "SALARY",
  "INVESTMENTS",
  "OTHER",
] as const;

export const INCOME_GROUP_CATEGORY = createLookup([...INCOME_GROUP_CATEGORIES]);

export const INCOME_GROUP_CATEGORY_BY_CATEGORY: Record<
  IncomeCategory,
  IncomeGroupCategory
> = {
  OTHER: INCOME_GROUP_CATEGORY.OTHER,
  INTEREST: INCOME_GROUP_CATEGORY.INVESTMENTS,
  DIVIDENDS: INCOME_GROUP_CATEGORY.INVESTMENTS,
  FULL_TIME: INCOME_GROUP_CATEGORY.SALARY,
  FREELANCE: INCOME_GROUP_CATEGORY.SALARY,
  PART_TIME: INCOME_GROUP_CATEGORY.SALARY,
  RENTAL_INCOME: INCOME_GROUP_CATEGORY.OTHER,
};

export const TRANSACTION_TYPES = ["EXPENSE", "INCOME"] as const;

export const TRANSACTION_TYPE = createLookup([...TRANSACTION_TYPES]);

export const INCOME_GROUP_CATEGORY_LABEL: Record<IncomeGroupCategory, string> =
  {
    [INCOME_GROUP_CATEGORY.INVESTMENTS]: "Inwestycje",
    [INCOME_GROUP_CATEGORY.OTHER]: "Inne",
    [INCOME_GROUP_CATEGORY.SALARY]: "Wynagrodzenie",
  };

export const INCOME_CATEGORY_LABEL: Record<IncomeCategory, string> = {
  [INCOME_CATEGORY.DIVIDENDS]: "Dywidendy",
  [INCOME_CATEGORY.FULL_TIME]: "Praca etatowa",
  [INCOME_CATEGORY.FREELANCE]: "Praca na zlecenie",
  [INCOME_CATEGORY.INTEREST]: "Odsetki",
  [INCOME_CATEGORY.OTHER]: "Inne",
  [INCOME_CATEGORY.PART_TIME]: "Praca dorywcza",
  [INCOME_CATEGORY.RENTAL_INCOME]: "Wynajem",
};
