import { createLookup, translate } from "@/shared/utils";
import { t } from "i18next";
import { ExpenseCategory } from "../types/expense";
import {
  ExpenseGroupCategory,
  IncomeCategory,
  IncomeGroupCategory,
} from "../types/shared";

export const EXPENSE_CATEGORIES: ExpenseCategory[] = [
  "FOOD",
  "TAKEAWAY",
  "ALCOHOL",
  "RENT",
  "UTILITIES",
  "MAINTENANCE",
  "PUBLIC_TRANSPORT",
  "FUEL",
  "CAR",
  "DOCTOR",
  "PHARMACY",
  "GYM",
  "CINEMA",
  "BOOKS",
  "OTHER",
];

export const EXPENSE_CATEGORY = createLookup(EXPENSE_CATEGORIES);

export const EXPENSE_GROUP_CATEGORIES = [
  "SHOPPING",
  "HOUSING",
  "TRANSPORT",
  "HEALTHCARE",
  "ENTERTAINMENT",
  "OTHER",
] as const;

export const EXPENSE_GROUP_CATEGORY = createLookup([
  ...EXPENSE_GROUP_CATEGORIES,
]);

export const EXPENSE_GROUP_CATEGORY_BY_CATEGORY: Record<
  ExpenseCategory,
  ExpenseGroupCategory
> = {
  FOOD: EXPENSE_GROUP_CATEGORY.SHOPPING,
  TAKEAWAY: EXPENSE_GROUP_CATEGORY.SHOPPING,
  ALCOHOL: EXPENSE_GROUP_CATEGORY.SHOPPING,
  RENT: EXPENSE_GROUP_CATEGORY.HOUSING,
  UTILITIES: EXPENSE_GROUP_CATEGORY.HOUSING,
  MAINTENANCE: EXPENSE_GROUP_CATEGORY.HOUSING,
  PUBLIC_TRANSPORT: EXPENSE_GROUP_CATEGORY.TRANSPORT,
  FUEL: EXPENSE_GROUP_CATEGORY.TRANSPORT,
  CAR: EXPENSE_GROUP_CATEGORY.TRANSPORT,
  DOCTOR: EXPENSE_GROUP_CATEGORY.HEALTHCARE,
  PHARMACY: EXPENSE_GROUP_CATEGORY.HEALTHCARE,
  GYM: EXPENSE_GROUP_CATEGORY.ENTERTAINMENT,
  CINEMA: EXPENSE_GROUP_CATEGORY.ENTERTAINMENT,
  BOOKS: EXPENSE_GROUP_CATEGORY.ENTERTAINMENT,
  OTHER: EXPENSE_GROUP_CATEGORY.OTHER,
};

export const INCOME_CATEGORIES: IncomeCategory[] = [
  "DIVIDENDS",
  "FULL_TIME",
  "FREELANCE",
  "INTEREST",
  "OTHER",
  "PART_TIME",
  "RENTAL_INCOME",
];

export const INCOME_CATEGORY = createLookup(INCOME_CATEGORIES);

export const INCOME_GROUP_CATEGORIES = [
  "SALARY",
  "INVESTMENTS",
  "OTHER",
] as const;

export const INCOME_GROUP_CATEGORY = createLookup([...INCOME_GROUP_CATEGORIES]);

export const INCOME_GROUP_CATEGORY_BY_CATEGORY: Record<
  IncomeCategory,
  IncomeGroupCategory
> = {
  OTHER: INCOME_GROUP_CATEGORY.OTHER,
  INTEREST: INCOME_GROUP_CATEGORY.INVESTMENTS,
  DIVIDENDS: INCOME_GROUP_CATEGORY.INVESTMENTS,
  FULL_TIME: INCOME_GROUP_CATEGORY.SALARY,
  FREELANCE: INCOME_GROUP_CATEGORY.SALARY,
  PART_TIME: INCOME_GROUP_CATEGORY.SALARY,
  RENTAL_INCOME: INCOME_GROUP_CATEGORY.OTHER,
};

export const TRANSACTION_TYPES = ["EXPENSE", "INCOME"] as const;

export const TRANSACTION_TYPE = createLookup([...TRANSACTION_TYPES]);
